---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy nginx configuration file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Ensure nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Install PHP-FPM
  apt:
    name: php-fpm
    state: present

- name: Copy PHP-FPM configuration file
  copy:
    src: php-fpm.conf
    dest: /etc/php/7.4/fpm/php-fpm.conf
  notify: Restart php-fpm

- name: Ensure php-fpm service is started and enabled
  service:
    name: php7.4-fpm
    state: started
    enabled: true

- name: Restart php-fpm
  service:
    name: php7.4-fpm
    state: restarted
