version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - loki
      - alertmanager
      - promtail

  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/loki
    command:
      - '-config.file=/etc/loki/local-config.yaml'
      - '-target=local'
    depends_on:
      - prometheus
      - alertmanager
      - promtail

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:8.3.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_PATHS_DATA=/var/lib/grafana/data
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
    command:
      - '-config.file=/etc/promtail/config.yml'
    depends_on:
      - loki

volumes:
  prometheus:
  loki:
  alertmanager:
  grafana: