version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yaml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/etc/grafana
    ports:
      - 3000:3000