server:
  http_listen_port: 9080

positions:
  filename: /data/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'docker-containers'
    static_configs:
      - targets:
          - 'localhost'
        labels:
          job: 'docker-containers'
          __path__: '/var/lib/docker/containers/*/*.log'