apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: "{{ .Values.db.postgresDatabase }}"
            - name: DB_USER
              value: "{{ .Values.db.postgresUser }}"
            - name: DB_PASS
              value: "{{ .Values.db.postgresPassword }}"
          volumeMounts:
            - name: app-data
              mountPath: /app
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-pvc