apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-pg-docker-tutorial.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-pg-docker-tutorial.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: "{{ .Values.db.postgresDatabase }}"
            - name: DB_USER
              value: "{{ .Values.db.postgresUser }}"
            - name: DB_PASS
              value: "{{ .Values.db.postgresPassword }}"
          volumeMounts:
            - name: app-data
              mountPath: /app
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-pvc