apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-pg.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-pg.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-pg.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.postgresDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.db.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.postgresPassword }}
          ports:
            - name: postgres
              containerPort: {{ .Values.db.service.port }}
              protocol: TCP
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "django-pg.fullname" . }}-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-pg.fullname" . }}-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "django-pg.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-pg.fullname" . }}-db-pvc
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  storageClassName: {{ .Values.db.persistence.storageClass }}