apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-helm-chart.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: app-data
              mountPath: /app
        - name: db
          image: {{ .Values.db.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: app-data
          emptyDir: {}
        - name: postgres-data
          persistentVolume