{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
  labels:
    {{ include "django-helm-chart.labels" . | indent 4 }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "django-helm-chart.fullname" . }}
                port:
                  number: {{ .Values.app.service.port }}
{{- end }}