{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-helm-chart.fullname" . }}-pvc
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}