apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}alues.storage.size }}