apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
  labels:
    {{- include "django-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"\",\"auth\":\"%s\"}}}" .Values.dockerhubUsername .Values.dockerhubAccessToken (printf "%s:%s" .Values.dockerhubUsername .Values.dockerhubAccessToken | b64enc) | b64enc }}