apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  type: {{ default "ClusterIP" .Values.app.service.type }}  # change here
  ports:
    - port: {{ .Values.app.service.port }}  # change here
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "django-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}