apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
  labels:
    {{ include "django-helm-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
  selector:
    {{ include "django-helm-chart.selectorLabels" . | indent 2 }}nt 4 }}