apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mychart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}