---
- name: Install required packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repo_added

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: docker_repo_added.changed

- name: Install Docker
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: Install Python pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Create users and add their public SSH keys
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"

    - name: Add public SSH key for user
      ansible.builtin.authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_key) }}"
        state: present
      loop: "{{ users }}"