---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repo_added

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: docker_repo_added.changed

- name: Install Docker
  ansible.builtin.package:
    name: docker-ce
    state: present

- name: Install Python pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Install binenv
  ansible.builtin.shell:
    cmd: |
      curl -LsSf https://github.com/devops-works/binenv/releases/latest/download/binenv_linux_amd64 > /usr/local/bin/binenv && chmod +x /usr/local/bin/binenv
      mkdir -p /root/.binenv/shim
  args:
    creates: /usr/local/bin/binenv

- name: Install kubectl using binenv
  ansible.builtin.shell:
    cmd: binenv install kubectl
  args:
    executable: /bin/bash

- name: Install Helm
  ansible.builtin.command:
    cmd: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
    creates: /usr/local/bin/helm
    args:
      warn: false
  become: yes

- name: Create users and add their public SSH keys
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
      loop: "{{ users }}"

    - name: Add public SSH key for user
      ansible.builtin.authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_key) }}"
        state: present
      loop: "{{ users }}"

- name: Install Ansible
  ansible.builtin.package:
    name: ansible
    state: present
...