---
- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx
- name: Create index.php
  copy:
    src: files/index.php
    dest: /usr/share/nginx/html/index.php
- name: Set ownership of index.php
  file:
    path: /usr/share/nginx/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'
