---
- name: Restart apache for RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart apache for Debian
  service: name-apache2 state=restarted
  when: ansible_os_family == "Debian"
