apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: myk8s-application
    env : prod
    owner: VMZ
  spec:
    replicas: 3
    selector:
      matchlabels:
        project: kgb
    template:
      metadata:
        labels:
          project: kgb
      containers:
        - name: kgb-web
        image: dreaddevil/k8sphp:latest
        ports:
          - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
  spec:
    scaleTargetRef:
      apiVersion: apps/v2
      kind: Deployment
      name: my-web-deployment-autoscaling
      minReplicas: 3
      maxReplicas: 5
      metrics:
        - type: Resourse
          resourse:
            name: cpu
            targetAverageUtilization: 70
        -type: Resourse
          resourse:
            name: memory
            targetAverageUtilization: 80
