---
- name: Install and start Docker on app servers
  hosts: app
  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present
    - name: Start Docker
      become: true
      service:
        name: docker
        state: started
- name: Install and start Postgresql on database servers
  hosts: database
  vars:
    postgres_version: "12"
    data_dir: "/var/lib/postgresql/{{ postgres_version }}/main/"
  tasks:
    - name: Install Postgresql
      become: true
      apt:
        name: postgresql-{{ postgres_version }}
        state: present
    - name: Start Postgresql
      become: true
      service:
        name: postgresql
        state: started
