---
- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Create index.php
  copy:
    src: files/index.php
    dest: /opt/nginx/ansible/index.php
  notify:
    - Reload nginx

- name: Set ownership of index.php
  file:
    path: /opt/nginx/ansible/index.php
    owner: www-data
    group: www-data
    mode: '0644'

handlers:
  - name: Reload nginx
    systemd:
      name: nginx
      state: restarted
