apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-helm-chart.fullname" . }}-app
  labels:
    {{- include "django-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "django-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: {{ .Values.app.env.DB_NAME }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-helm-chart.fullname" . }}-secrets
                  key: app-db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-helm-chart.fullname" . }}-secrets
                  key: app-db-pass
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.db.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-helm-chart.fullname" . }}-secrets
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-helm-chart.fullname" . }}-secrets
                  key: db-password
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "django-helm-chart.fullname" . }}-db
      imagePullSecrets:
        - name: {{ include "django-helm-chart.fullname" . }}-secrets