---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-helm-chart.fullname" . }}-secrets
  labels:
    {{- include "django-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ .Values.db.env.POSTGRES_USER | b64enc }}
  db-password: {{ .Values.db.env.POSTGRES_PASSWORD | b64enc }}
  app-db-user: {{ .Values.app.env.DB_USER | b64enc }}
  app-db-pass: {{ .Values.app.env.DB_PASS | b64enc }}
  docker-username: {{ .Values.dockerhubUsername | b64enc }}
  docker-password: {{ .Values.dockerhubAccessToken | b64enc }}