---
# tasks file for deploy_apache_web
- block:  #RedHat#
  - name: Install Apache Web Server for RedHat
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: Start WebServer and make it enable on boot for RedHat
    service: name=httpd state=started enable=yes

- block: #Debian#
  - name: Install Web Server for Debian
    apt: name=apache2 state=latest
    when: ansible_os_family != "RedHat"

  - name: Start WebServer and make it enable on boot for Debian
    service: name=apache2 state=started enable=yes
    when: ansible_os_family == "Debian"

- name: Copy MyHomePage to servers
  copy: src={{item}} dest={{ destin_folder }} mode=0555
#   copy: src={{item}} dest={{ destin_folder }} mode=0555
#   with_fileglob: "{{ source_folder  }}/*.*"
  loop:
    - "index.html"
    - "index.jpg"
  notify:
    - Restart Apache for Debian
    - Restart Apache for RedHat
