version: '3'

services:
  php:
    build: .
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://nginx | grep -q works"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/dev.conf
    depends_on:
      - php