---
- name: Install Docker, Docker Compose and add public SSH keys
  hosts: server
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present
      register: docker_installed

    - name: Install Docker Compose
      ansible.builtin.package:
        name: docker-compose
        state: present
      when: docker_installed is changed

    - name: Add public SSH keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', item) }}"
        state: present
      loop:
        - "C:\Users\DreadDevil\.ssh\id_rsa"