apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80 # Порт контейнера приложения
          env:
            # Здесь можно определить переменные окружения для приложения
            - name: DB_HOST
              value: {{ .Release.Name }}-db
            - name: DB_USER
              value: {{ .Values.db.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.db.dbPassword }}
            - name: DB_NAME
              value: {{ .Values.db.dbName }}
      volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: app-data
          mountPath: /data # Путь для монтирования PVC
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-pvc
  {{- end }}