---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
  source_folder: ./MyWebSite/
  destin_folder: ./var/www/html

  tasks:
    - block:  #RedHat#
      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest
        when: ansible_os_family == "RedHat"

      - name: Start WebServer and make it enable on boot for RedHat
        service: name=httpd state=started enable=yes

    - block: #Debian#
      - name: Install Web Server for Debian
        apt: name=apache2 state=latest
        when: ansible_os_family != "RedHat"

      - name: Start WebServer and make it enable on boot for Debian
        service: name=apache2 state=started enable=yes
        when: ansible_os_family == "Debian"

    - name: Copy MyHomePage to servers
      copy: src={{ source_folder }}/{{item}} dest={{ destin_folder }} mode=0555
#     copy: src={{item}} dest={{ destin_folder }} mode=0555
#     with_fileglob: "{{ source_folder  }}/*.*"
      loop:
        - "index.html"
        - "index.jpg"
      notify:
        - Restart Apache for Debian
        - Restart Apache for RedHat

handlers:
  - name: Restart apache for RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart apache for Debian
    service: name-apache2 state=restarted
    when: ansible_os_family == "Debian"
