---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes
  #any_errors_fatal: true

  vars:
  source_folder: ./MyWebSite/
  destin_folder: ./var/www/html

  tasks:
    - name: Show linux version
      debug: var=ansible_os_family

    - name: Copy MyHomePage to servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555

    - name: Loop Hello
      debug: msg="Hello {{ item }}"
      loop:
        - "One"
        - "Two"
        - "Three"

    - name: Loop until
      shell: echo -n Z >> myile.txt && cat myfile.txt
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find{"ZZZZ"} == false

    - name: Generate INDEX.HTM
      template: src={{ source_folder }}/index.j2 dest={{ destin_file }} mode=0555

    - name: ping
      ping:

    - name: task
      register: results
      failed_when: results.rc == 0
#      failed_when: "'Word' in results.stdout"
#      ignore_errors: yes

    - name: Create smth
      include: test.yml
      import: test2.yml

    - name: Reboot my servers
      shell: sleep 3 && reboot now
      async: 1
      poll: 0

    - name: Wait till my servers will come up
      wait_for:
        host: {{ inventory_hostname }}
        state: started
        delay: 5
        timeout: 40
      delegate_to: 127.0.0.1
