replicaCount: 1

image:
  repository: your_dockerhub_username/your_repository_name
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3003

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]

db:
  image: postgres:13-alpine
  name: tutorial-dev
  user: vinhle
  password: password
  port: 5432

pvc:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

secret:
  name: django-db-credentials
Создайте файлы шаблонов в каталоге templates:
deployment.yaml:
yaml
Copy code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-helm-chart.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: app-data
              mountPath: /app
        - name: db
          image: {{ .Values.db.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: app-data
          emptyDir: {}
        - name: postgres-data
          persistentVolume