app:
  replicas: 1
  image: dreaddevil/django-pg-docker-tutorial
  tag: latest
  service:
    type: NodePort
    port: 3003
  ingress:
    enabled: true
    annotations: {}
    hosts: []
  resources: {}

db:
  image: postgres:13-alpine
  service:
    type: ClusterIP
    port: 5432
  resources: {}
  persistence:
    enabled: true
    size: 1Gi  # <----- Adjust the size here