app:
  replicas: 1
  image:
    repository: dreaddevil/django-pg-docker-tutorial
    tag: latest
  service:
    type: ClusterIP
    port: 3003
  env:
    DB_HOST: db
    DB_NAME: tutorial-dev
    DB_USER: vinhle
    DB_PASS: password

db:
  image: postgres:13-alpine
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_DB: tutorial-dev
    POSTGRES_USER: vinhle
    POSTGRES_PASSWORD: password

volumeClaim:
  enabled: true
  name: tutorial-volume
  size: 1Gi

ingress:
  enabled: false
  hosts: []to/app