"""Initial migration

Revision ID: 6bbbe527357a
Revises: 
Create Date: 2024-10-07 00:17:01.737376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bbbe527357a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_name'), ['name'], unique=True)

    op.create_table('user_table_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    op.drop_table('user_table_access')
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_name'))

    op.drop_table('table')
    # ### end Alembic commands ###
