version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  loki:
    image: grafana/loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command:
      - "-config.file=/etc/promtail/config.yaml"
      - "-client.url=http://loki:3100/loki/api/v1/push"
      - "-client.external-labels=job=app"
