---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-helm-chart.fullname" . }}
  labels:
    {{- include "django-helm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}